### ISSUE TITLE
Windows Service Pack 1 Error

### ISSUE THREAD

**Issue by GamerDev197** [Ascript89/adobe-periodic-table#1]
Hi I try to install Adobe Periodic Table and I got an error "This program requires Windows Service Pack 1 or later". My Computer is in Windows 10 Pro
![qw](https://user-images.githubusercontent.com/106304863/198875624-d6efb2d6-4855-457d-92dd-ee1c71416deb.PNG)

**Comment by Ascript89** [comment]
If that's something that happened with the installer, make sure you're running on an updated Windows 10/11 machine, up to the latest version. Honestly, that message doesn't make any sense, as SP1 was for WinXP and Win7. Pretty weird.

If you are already up to date with Windows 10, please send me a video showing the installation & error process.

**Comment by GamerDev197** [comment]
> If that's something that happened with the installer, make sure you're running on an updated Windows 10/11 machine, up to the latest version. Honestly, that message doesn't make any sense, as SP1 was for WinXP and Win7. Pretty weird.
> 
> If you are already up to date with Windows 10, please send me a video showing the installation & error process.


https://user-images.githubusercontent.com/106304863/199027332-af1648dc-6afe-42fa-909e-1aa2df2f99f5.mp4

**Comment by Ascript89** [comment]
Thanks for that video. Following the video steps, it's likely to be an installer error, even though your Windows version is outdated. I'll be sending you a copy of the program without the installer.

**Comment by GamerDev197** [comment]
> Thanks for that video. Following the video steps, it's likely to be an installer error, even though your Windows version is outdated. I'll be sending you a copy of the program without the installer.

thank you

**Comment by Ascript89** [comment]
Hello, here's the program folder with all its content: https://www.mediafire.com/file/heuq3zuq06bwfnp/Adobe_Periodic_Table.rar/file

I recommend you to place it on "C:\Program Files (x86)", just in case anything fails in the updater when new versions are released.

**Comment by GamerDev197** [comment]
> Hello, here's the program folder with all its content: https://www.mediafire.com/file/heuq3zuq06bwfnp/Adobe_Periodic_Table.rar/file
> 
> I recommend you to place it on "C:\Program Files (x86)", just in case anything fails in the updater when new versions are released.

Ok it Works perfectly, thank you for giving me the .rar file
